# Generated by Django 4.0.3 on 2022-03-15 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 15, 47, 36, 284243, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table='chihab_blogs',
        ),
    ]
