# Generated by Django 4.0.3 on 2022-03-15 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 15, 47, 56, 258168, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
