# Generated by Django 3.2.10 on 2022-03-18 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220318_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 20, 14, 3, 451145, tzinfo=utc)),
        ),
    ]
