# Generated by Django 3.2.10 on 2022-03-20 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220320_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 16, 18, 39, 515799, tzinfo=utc)),
        ),
    ]
